name: CI/CD Deploy to EC2 via Helm

on:
  push:
    branches: [ "main" ]

jobs:
  build_push_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build & Push API Image
        run: |
          docker build -t {{ secrets.DOCKERHUB_USERNAME }}/api-microservice:latest ./api
          docker tag {{ secrets.DOCKERHUB_USERNAME }}/api-microservice:latest {{ secrets.DOCKERHUB_USERNAME }}/api-microservice:${{ github.sha }}
          docker push {{ secrets.DOCKERHUB_USERNAME }}/api-microservice:latest
          docker push {{ secrets.DOCKERHUB_USERNAME }}/api-microservice:${{ github.sha }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t {{ secrets.DOCKERHUB_USERNAME }}/frontend-microservice:latest ./frontend
          docker tag {{ secrets.DOCKERHUB_USERNAME }}/frontend-microservice:latest {{ secrets.DOCKERHUB_USERNAME }}/frontend-microservice:${{ github.sha }}
          docker push {{ secrets.DOCKERHUB_USERNAME }}/frontend-microservice:latest
          docker push {{ secrets.DOCKERHUB_USERNAME }}/frontend-microservice:${{ github.sha }}     

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_ec2
          chmod 600 ~/.ssh/github_ec2
          ssh-keyscan -H 34.226.99.222 >> ~/.ssh/known_hosts

      - name: Deploy via SSH & Helm
        run: |
         ssh -T -i ~/.ssh/github_ec2 ubuntu@34.226.99.222 << EOF
         set -e
         export TAG=${TAG}

         cd ~/microservice-project
         git fetch origin
         git reset --hard origin/main

         helm uninstall microservices --ignore-not-found --wait

         helm upgrade --install microservices ./microservices-chart

          kubectl get pods -o wide
          kubectl get svc
         EOF

